language: node_js
node_js:
    - "stable"
script:
   - yarn install
   - yarn test
   - yarn run build

deploy:
    provider: surge
    skip_cleanup: true
    domain: thirsty-fold.surge.sh
    project: ./build/
on:
   branch: master